version: "3.9"
services:
    compiler:
      container_name: middleware-compiler
      build:
        context: middleware
        dockerfile: Dockerfile
      volumes:
        - "./middleware:/code"
      ports:
        - "8989:8989"
      entrypoint: /bin/sh
      stdin_open: true
      tty: true
